<div class="container">
    
    <div class="block block-condensed">
        <!-- START HEADING -->
        <div class="app-heading app-heading-small">
            <div class="title">
                <h5>Productos</h5>
                <p>Administración de productos.</p>
            </div>
        </div>
        <!-- END HEADING -->
        
        <div class="block-content">
            <div class="alert alert-success alert-icon-block alert-dismissible" role="alert">
                <div class="alert-icon">
                    <span class="icon-checkmark-circle"></span> 
                </div>
                <strong>Success!</strong> You successfully read this important alert message. 
                <button type="button" class="close" data-dismiss="alert" aria-label="Close"><span class="fa fa-times"></span></button>
            </div>  

            <div class="alert alert-warning alert-icon-block alert-dismissible" role="alert"> 
                <div class="alert-icon">
                    <span class="icon-chart-bars"></span> 
                </div>
                <strong>Warning!</strong> Better check yourself, you're not looking too good. 
                <button type="button" class="close" data-dismiss="alert" aria-label="Close"><span class="fa fa-times"></span></button>
            </div>                                 

            <div class="alert alert-danger alert-icon-block alert-dismissible" role="alert"> 
                <div class="alert-icon">
                    <span class="icon-menu-circle"></span> 
                </div>                                        
                <strong>Danger!</strong> Change a few things up and try submitting again. 
                <button type="button" class="close" data-dismiss="alert" aria-label="Close"><span class="fa fa-times"></span></button>
            </div>                                

            
            <div class="form-group">
                <div class="col-md-4">
                    <div class="btn-group">
                        <a href="<?= $this->url('product', ['action' => 'add']) ?>" class="btn btn-default">Agregar nuevo</a>
                        <button type="button" class="btn btn-default dropdown-toggle" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                            Acciones <span class="caret"></span>
                        </button>
                        <ul class="dropdown-menu">
                            <li><a href="#">Action</a></li>
                            <li><a href="#">Another action</a></li>
                            <li><a href="#">Something else here</a></li>
                            <li role="separator" class="divider"></li>
                            <li><a href="#">Separated link</a></li>
                        </ul>
                    </div>                      
                </div>
            </div>

            <table class="table table-striped table-bordered datatable-extended">
                <thead>
                    <tr>
                        <th>ID</th>
                        <th>Nombre</th>
                        <th>Stock</th>
                        <th> </th>
                    </tr>
                </thead>                                    
                <tbody>

                <?php foreach ($products as $product) : ?>
                    <tr>
                        <td><?= $this->escapeHtml($product->id_product) ?></td>
                        <td><?= $this->escapeHtml($product->name) ?></td>
                        <td><?= $this->escapeHtml($product->stock) ?></td>
                        <td width="30">
                            <div class="dropdown">
                                <button class="btn btn-default btn-icon btn-clean dropdown-toggle" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false"><span class="icon-cog"></span></button>
                                <ul class="dropdown-menu dropdown-left">
                                    <li><a href="<?= $this->url('product', ['action' => 'edit', 'id' => $product->id_product]) ?>"><span class="icon-pencil text-info"></span> Editar</a></li> 
                                    <li><a href="<?= $this->url('product', ['action' => 'element', 'id' => $product->id_product]) ?>"><span class="icon-picture text-warning"></span> Imágenes</a></li> 
                                    <li class="divider"></li>
                                    <li><a href="<?= $this->url('product', ['action' => 'delete', 'id' => $product->id_product]) ?>"><span class="icon-trash text-danger"></span> Eliminar</a></li> 
                                </ul>
                            </div>                        
                        </td>
                    </tr>
                <?php endforeach; ?>                                    
                </tbody>
            </table>
            
        </div>
        
    </div>
    
</div>