<!DOCTYPE html>
<html lang="en">
    <head>                        
        <title>Idealshop - Login</title>            
        
        <!-- META SECTION -->
        <meta http-equiv="Content-Type" content="text/html; charset=utf-8">
        <meta http-equiv="X-UA-Compatible" content="IE=edge">
        <meta name="viewport" content="width=device-width, initial-scale=1">
        
        <link rel="shortcut icon" href="favicon.ico" type="image/x-icon">
        <link rel="icon" href="favicon.ico" type="image/x-icon">
        <!-- END META SECTION -->
        <!-- CSS INCLUDE -->        
        <link rel="stylesheet" href="<?php echo $this->serverUrl(); ?>/css/styles.css">
        <!-- EOF CSS INCLUDE -->
    </head>
    <body>        
        
        <!-- APP WRAPPER -->
        <div class="app">

            <!-- START APP CONTAINER -->
            <?= $this->content ?>
            <!-- END APP CONTAINER -->
           
        </div>        
        <!-- END APP WRAPPER -->                
        
        <!-- START SCRIPTS -->
        <script type="text/javascript" src="<?php echo $this->serverUrl(); ?>/js/vendor/jquery/jquery.min.js"></script>
        <script type="text/javascript" src="<?php echo $this->serverUrl(); ?>/js/vendor/jquery/jquery-ui.min.js"></script>
        <script type="text/javascript" src="<?php echo $this->serverUrl(); ?>/js/vendor/bootstrap/bootstrap.min.js"></script>
        <script type="text/javascript" src="<?php echo $this->serverUrl(); ?>/js/vendor/moment/moment.min.js"></script>       
        
        <script type="text/javascript" src="<?php echo $this->serverUrl(); ?>/js/vendor/customscrollbar/jquery.mCustomScrollbar.min.js"></script>
        <script type="text/javascript" src="<?php echo $this->serverUrl(); ?>/js/vendor/bootstrap-select/bootstrap-select.js"></script>
        <script type="text/javascript" src="<?php echo $this->serverUrl(); ?>/js/vendor/select2/select2.full.min.js"></script>
        <script type="text/javascript" src="<?php echo $this->serverUrl(); ?>/js/vendor/bootstrap-datetimepicker/bootstrap-datetimepicker.js"></script>
        
        <script type="text/javascript" src="<?php echo $this->serverUrl(); ?>/js/vendor/maskedinput/jquery.maskedinput.min.js"></script>
        <script type="text/javascript" src="<?php echo $this->serverUrl(); ?>/js/vendor/form-validator/jquery.form-validator.min.js"></script>
        
        <script type="text/javascript" src="<?php echo $this->serverUrl(); ?>/js/vendor/noty/jquery.noty.packaged.js"></script>
        
        <script type="text/javascript" src="<?php echo $this->serverUrl(); ?>/js/vendor/datatables/jquery.dataTables.min.js"></script>
        <script type="text/javascript" src="<?php echo $this->serverUrl(); ?>/js/vendor/datatables/dataTables.bootstrap.min.js"></script>
        
        <script type="text/javascript" src="<?php echo $this->serverUrl(); ?>/js/vendor/sweetalert/sweetalert.min.js"></script>
        <script type="text/javascript" src="<?php echo $this->serverUrl(); ?>/js/vendor/knob/jquery.knob.min.js"></script>
        
        <script type="text/javascript" src="<?php echo $this->serverUrl(); ?>/js/vendor/jvectormap/jquery-jvectormap.min.js"></script>
        <script type="text/javascript" src="<?php echo $this->serverUrl(); ?>/js/vendor/jvectormap/jquery-jvectormap-world-mill-en.js"></script>
        <script type="text/javascript" src="<?php echo $this->serverUrl(); ?>/js/vendor/jvectormap/jquery-jvectormap-us-aea-en.js"></script>
        
        <script type="text/javascript" src="<?php echo $this->serverUrl(); ?>/js/vendor/sparkline/jquery.sparkline.min.js"></script>
        
        <script type="text/javascript" src="<?php echo $this->serverUrl(); ?>/js/vendor/morris/raphael.min.js"></script>
        <script type="text/javascript" src="<?php echo $this->serverUrl(); ?>/js/vendor/morris/morris.min.js"></script>
        
        <script type="text/javascript" src="<?php echo $this->serverUrl(); ?>/js/vendor/rickshaw/d3.v3.js"></script>
        <script type="text/javascript" src="<?php echo $this->serverUrl(); ?>/js/vendor/rickshaw/rickshaw.min.js"></script>
        
        <script type="text/javascript" src="<?php echo $this->serverUrl(); ?>/js/vendor/isotope/isotope.pkgd.min.js"></script>
        
        <script type="text/javascript" src="<?php echo $this->serverUrl(); ?>/js/vendor/dropzone/dropzone.js"></script>
        <script type="text/javascript" src="<?php echo $this->serverUrl(); ?>/js/vendor/nestable/jquery.nestable.js"></script>
        <script type="text/javascript" src="<?php echo $this->serverUrl(); ?>/js/vendor/cropper/cropper.min.js"></script>
        
        <script type="text/javascript" src="<?php echo $this->serverUrl(); ?>/js/vendor/tableexport/tableExport.js"></script>
        <script type="text/javascript" src="<?php echo $this->serverUrl(); ?>/js/vendor/tableexport/jquery.base64.js"></script>
        <script type="text/javascript" src="<?php echo $this->serverUrl(); ?>/js/vendor/tableexport/html2canvas.js"></script>
        <script type="text/javascript" src="<?php echo $this->serverUrl(); ?>/js/vendor/tableexport/jspdf/libs/sprintf.js"></script>
        <script type="text/javascript" src="<?php echo $this->serverUrl(); ?>/js/vendor/tableexport/jspdf/jspdf.js"></script>
        <script type="text/javascript" src="<?php echo $this->serverUrl(); ?>/js/vendor/tableexport/jspdf/libs/base64.js"></script> 
        
        <script type="text/javascript" src="<?php echo $this->serverUrl(); ?>/js/app.js"></script>
        <script type="text/javascript" src="<?php echo $this->serverUrl(); ?>/js/app_plugins.js"></script>
        <script type="text/javascript" src="<?php echo $this->serverUrl(); ?>/js/app_demo.js"></script>
        <!-- END SCRIPTS -->
    </body>
</html>