<!DOCTYPE html>
<html lang="en">
    <head>                        
        <title>Idealshop - Sistema de administración</title>            
        
        <!-- META SECTION -->
        <meta http-equiv="Content-Type" content="text/html; charset=utf-8">
        <meta http-equiv="X-UA-Compatible" content="IE=edge">
        <meta name="viewport" content="width=device-width, initial-scale=1">
        
        <link rel="shortcut icon" href="favicon.ico" type="image/x-icon">
        <link rel="icon" href="favicon.ico" type="image/x-icon">
        <base href="<?php echo $this->serverUrl(); ?>" />
        <!-- END META SECTION -->
        <!-- CSS INCLUDE -->        
        <link rel="stylesheet" href="<?php echo $this->serverUrl(); ?>/css/styles.css">
        <!-- EOF CSS INCLUDE -->
    </head>
    <body>        
        
        <!-- APP WRAPPER -->
        <div class="app">           

            <!-- START APP CONTAINER -->
            <div class="app-container">
                <!-- START SIDEBAR -->
                <div class="app-sidebar app-navigation app-navigation-fixed scroll app-navigation-style-default app-navigation-open-hover dir-left" data-type="close-other">
                    <a href="index.html" class="app-navigation-logo">
                        Boooya - Revolution Admin Template
                        <button class="app-navigation-logo-button mobile-hidden" data-sidepanel-toggle=".app-sidepanel"><span class="icon-alarm"></span> <span class="app-navigation-logo-button-alert">7</span></button>
                    </a>
                    <nav>
                        <ul>
                            <li class="title">MAIN</li>
                            <li><a href="index.html"><span class="nav-icon-hexa">Ds</span> Dashboard</a></li>
                            <li>
                                <a href="#"><span class="nav-icon-hexa">Pg</span> Pages</a>
                                <ul>                                
                                    <li><a href="pages-faq.html"><span class="nav-icon-hexa">Fq</span> FAQ</a></li>
                                    <li><a href="pages-gallery.html"><span class="nav-icon-hexa">Ga</span> Gallery</a></li>
                                    <li><a href="pages-help.html"><span class="nav-icon-hexa">Hp</span> Help</a></li>
                                    <li><a href="pages-search.html"><span class="nav-icon-hexa">Sr</span> Search Result</a></li>
                                    <li>
                                        <a href="#"><span class="nav-icon-hexa">Pf</span> User Profiles</a>
                                        <ul>
                                            <li><a href="pages-profile-social.html"><span class="nav-icon-hexa">Sp</span> Social Profile</a></li>
                                            <li><a href="pages-profile-card.html"><span class="nav-icon-hexa">Pc</span> Profile Card</a></li>                
                                        </ul>
                                    </li>
                                    <li>
                                        <a href="#"><span class="nav-icon-hexa">Ba</span> Bank Application</a>
                                        <ul>                
                                            <li><a href="pages-bank-main.html"><span class="nav-icon-hexa">Mn</span> Main</a></li>
                                            <li><a href="pages-bank-deposits.html"><span class="nav-icon-hexa">Dp</span> Deposits</a></li>
                                            <li><a href="pages-bank-activity.html"><span class="nav-icon-hexa">Ac</span> Activity</a></li>
                                            <li><a href="pages-bank-settings.html"><span class="nav-icon-hexa">St</span> Settings</a></li>
                                            <li><a href="pages-bank-security.html"><span class="nav-icon-hexa">Sc</span> Security</a></li>
                                        </ul>
                                    </li>
                                    <li>
                                        <a href="#"><span class="nav-icon-hexa">Bp</span> Blog Pages</a>
                                        <ul>                
                                            <li><a href="pages-blog-main.html"><span class="nav-icon-hexa">Ma</span> Main (Variant 1)</a></li>
                                            <li><a href="pages-blog-main-2.html"><span class="nav-icon-hexa">Mn</span> Main (Variant 2)</a></li>
                                            <li><a href="pages-blog-category.html"><span class="nav-icon-hexa">Ct</span> Category (Right Sidebar)</a></li>
                                            <li><a href="pages-blog-category-2.html"><span class="nav-icon-hexa">Cr</span> Category (Left Sidebar)</a></li>
                                            <li><a href="pages-blog-single.html"><span class="nav-icon-hexa">Sn</span> Single</a></li>                        
                                        </ul>
                                    </li>
                                    <li><a href="pages-contact-list.html"><span class="nav-icon-hexa">Cl</span> Contact List</a></li>
                                    <li>
                                        <a href="#"><span class="nav-icon-hexa">Ms</span> Messages</a>
                                        <ul>
                                            <li><a href="pages-messages-chat.html"><span class="nav-icon-hexa">Ct</span> Chat</a></li>
                                            <li><a href="pages-messages-list.html"><span class="nav-icon-hexa">Ml</span> Messages List</a></li>
                                        </ul>
                                    </li>
                                    <li><a href="pages-lock-screen.html"><span class="nav-icon-hexa">Ls</span> Lock Screen</a></li>
                                    <li>
                                        <a href="#"><span class="nav-icon-hexa">Si</span> Log In / Sign In</a>
                                        <ul>
                                            <li><a href="pages-login.html"><span class="nav-icon-hexa">Li</span> Log In</a></li>
                                            <li><a href="pages-login-bg.html"><span class="nav-icon-hexa">Lb</span> Log In (Background)</a></li>
                                            <li><a href="pages-signin.html"><span class="nav-icon-hexa">Si</span> Sign In</a></li>
                                            <li><a href="pages-signin-bg.html"><span class="nav-icon-hexa">Sb</span> Sign In (Background)</a></li>
                                        </ul>
                                    </li>
                                </ul>
                            </li>                
                            <li><a href="documentation.html"><span class="nav-icon-hexa">Dc</span> Documentation</a></li>
                            
                            <li class="title">PRODUCTOS</li>      
                            <li>
                                <a href="/product"><span class="nav-icon-hexa">Pr</span> Productos</a>
                            </li>          
                            <li>
                                <a href="/product/add"><span class="nav-icon-hexa">Ag</span> Agregar</a>
                            </li>
                            <li>
                                <a href="/product/category"><span class="nav-icon-hexa">Ct</span> Categoría</a>                        
                            </li>
                            
                            <li class="title">PEDIDOS</li>
                            <li>
                                <a href="#"><span class="nav-icon-hexa">Ls</span> Lista</a>
                            </li>                            
                            <li class="title">TIENDA</li>
                            <li>
                                <a href="#"><span class="nav-icon-hexa">Lt</span> Lista</a>
                            </li>
                            <li class="title">UBIGEO</li>
                            <li>
                                <a href="#"><span class="nav-icon-hexa">Lt</span> Lista</a>         
                            </li>
                            <li class="title">DELIVERY</li>
                            <li><a href="rtl.html"><span class="nav-icon-hexa">Lt</span> Lista</a></li>
                            <li class="title">USUARIO</li>
                            <li><a href="rtl.html"><span class="nav-icon-hexa">Rs</span> Lista</a></li>
                            <li><a href="rtl.html"><span class="nav-icon-hexa">Ag</span> Agregar</a></li>
                            <li class="title">REPORTES</li>
                            <li><a href="rtl.html"><span class="nav-icon-hexa">Dr</span> Diario</a></li>
                            <li><a href="rtl.html"><span class="nav-icon-hexa">Vt</span> Ventas</a></li>
                            <li><a href="rtl.html"><span class="nav-icon-hexa">Vs</span> Visitas</a></li>
                        </ul>
                    </nav>
                </div>
                <!-- END SIDEBAR -->
                
                <!-- START APP CONTENT -->
                <div class="app-content app-sidebar-left">
                    <!-- START APP HEADER -->
                    <div class="app-header">
                        <ul class="app-header-buttons">
                            <li class="visible-mobile"><a href="#" class="btn btn-link btn-icon" data-sidebar-toggle=".app-sidebar.dir-left"><span class="icon-menu"></span></a></li>
                            <li class="hidden-mobile"><a href="#" class="btn btn-link btn-icon" data-sidebar-minimize=".app-sidebar.dir-left"><span class="icon-list"></span></a></li>
                        </ul>
                        <form class="app-header-search" action="" method="post">        
                            <input type="text" name="keyword" placeholder="Search">
                        </form>    
                    
                        <ul class="app-header-buttons pull-right">
                            <li>
                                <div class="contact contact-rounded contact-bordered contact-lg contact-ps-controls">
                                    <img src="assets/images/users/user_1.jpg" alt="John Doe">
                                    <div class="contact-container">
                                        <a href="#">Estibens Manchego</a>
                                        <span>Administrator</span>
                                    </div>
                                    <div class="contact-controls">
                                        <div class="dropdown">
                                            <button type="button" class="btn btn-default btn-icon" data-toggle="dropdown"><span class="icon-cog"></span></button>                        
                                            <ul class="dropdown-menu dropdown-left">
                                                <li><a href="#"><span class="icon-cog"></span> Settings</a></li> 
                                                <li><a href="#"><span class="icon-envelope"></span> Messages <span class="label label-danger pull-right">+24</span></a></li>
                                                <li><a href="#"><span class="icon-users"></span> Contacts <span class="label label-default pull-right">76</span></a></li>
                                                <li class="divider"></li>
                                                <li><a href="#"><span class="icon-exit"></span> Log Out</a></li> 
                                            </ul>
                                        </div>                    
                                    </div>
                                </div>
                            </li>        
                        </ul>
                    </div>
                    <!-- END APP HEADER  -->
                    
                    <!-- START PAGE HEADING -->
                    <div class="app-heading app-heading-bordered app-heading-page">
                        <div class="icon icon-lg">
                            <span class="icon-laptop-phone"></span>
                        </div>
                        <div class="title">
                            <h1>Idealshop - Dashboard</h1>
                            <p>Sistema de administración general</p>
                        </div>               
                        
                    </div>
                    <div class="app-heading-container app-heading-bordered bottom">
                        <ul class="breadcrumb">
                            <li><a href="/">Dashboard</a></li>                                                     
                            <li class="active">Productos</li>
                        </ul>
                    </div>
                    <!-- END PAGE HEADING -->
                    
                    <!-- START PAGE CONTAINER -->
                    <?= $this->content ?>
                    <!-- END PAGE CONTAINER -->
                    
                </div>
                <!-- END APP CONTENT -->
                                
            </div>
            <!-- END APP CONTAINER -->
                        
            <!-- START APP FOOTER -->
            <div class="app-footer app-footer-default" id="footer">
            
                <div class="alert alert-primary alert-dismissible alert-inside text-center">
                    <button type="button" class="close" data-dismiss="alert" aria-label="Close"><span class="icon-cross"></span></button>
                    We use cookies to offer you the best experience on our website. Continuing browsing, you accept our cookies policy.
                </div>
            
                <div class="app-footer-line extended">
                    <div class="row">
                        <div class="col-md-3 col-sm-4">
                            <h3 class="title"><img src="/img/logo-footer.png" alt="boooyah"> Boooya</h3>                            
                            <p>The innovation in admin template design. You will save hundred hours while working with our template. That is based on latest technologies and understandable for all.</p>
                            <p><strong>How?</strong><br>This template included with thousand of best components, that really help you to build awesome design.</p>
                        </div>
                        <div class="col-md-2 col-sm-4">
                            <h3 class="title"><span class="icon-clipboard-text"></span> About Us</h3>
                            <ul class="list-unstyled">
                                <li><a href="#">About</a></li>                                                                
                                <li><a href="#">Team</a></li>
                                <li><a href="#">Why use us?</a></li>
                                <li><a href="#">Careers</a></li>
                            </ul>
                        </div>
                        <div class="col-md-2 col-sm-4">                            
                            <h3 class="title"><span class="icon-lifebuoy"></span> Need Help?</h3>
                            <ul class="list-unstyled">
                                <li><a href="#">FAQ</a></li>                                                                
                                <li><a href="#">Community</a></li>
                                <li><a href="#">Contacts</a></li>
                                <li><a href="#">Terms & Conditions</a></li>
                            </ul>
                        </div>
                        <div class="col-md-3 col-sm-6 clear-mobile">
                            <h3 class="title"><span class="icon-reading"></span> Latest News</h3>
            
                            <div class="row app-footer-articles">
                                <div class="col-md-3 col-sm-4">
                                    <img src="/assets/images/preview/img-1.jpg" alt="" class="img-responsive">
                                </div>
                                <div class="col-md-9 col-sm-8">
                                    <a href="#">Best way to increase vocabulary</a>
                                    <p>Quod quam magnum sit fictae veterum fabulae declarant, in quibus tam multis.</p>
                                </div>
                            </div>
            
                            <div class="row app-footer-articles">
                                <div class="col-md-3 col-sm-4">
                                    <img src="/assets/images/preview/img-2.jpg" alt="" class="img-responsive">
                                </div>
                                <div class="col-md-9 col-sm-8">
                                    <a href="#">Best way to increase vocabulary</a>
                                    <p>In quibus tam multis tamque variis ab ultima antiquitate repetitis tria.</p>
                                </div>
                            </div>
            
                        </div>
                        <div class="col-md-2 col-sm-6">
                            <h3 class="title"><span class="icon-thumbs-up"></span> Social Media</h3>
            
                            <a href="#" class="label-icon label-icon-footer label-icon-bordered label-icon-rounded label-icon-lg">
                                <i class="fa fa-facebook"></i>
                            </a>
                            <a href="#" class="label-icon label-icon-footer label-icon-bordered label-icon-rounded label-icon-lg">
                                <i class="fa fa-twitter"></i>
                            </a>
                            <a href="#" class="label-icon label-icon-footer label-icon-bordered label-icon-rounded label-icon-lg">
                                <i class="fa fa-youtube"></i>
                            </a>
                            <a href="#" class="label-icon label-icon-footer label-icon-bordered label-icon-rounded label-icon-lg">
                                <i class="fa fa-google-plus"></i>
                            </a>
                            <a href="#" class="label-icon label-icon-footer label-icon-bordered label-icon-rounded label-icon-lg">
                                <i class="fa fa-feed"></i>
                            </a>
            
                            <h3 class="title"><span class="icon-paper-plane"></span> Subscribe</h3>
            
                            <div class="input-group">
                                <input type="text" class="form-control" placeholder="E-mail...">
                                <div class="input-group-btn">
                                    <button class="btn btn-primary">GO</button>
                                </div>
                            </div> 
                        </div>                        
                    </div>                    
                </div>
                <div class="app-footer-line darken">                
                    <div class="copyright wide text-center">&copy; 2016 Boooya. All right reserved in the Ukraine and other countries.</div>                
                </div>
            </div>
            <!-- END APP FOOTER -->

            <!-- START APP SIDEPANEL -->
            <div class="app-sidepanel scroll" data-overlay="show">                
                <div class="container">
                    
                    <div class="app-heading app-heading-condensed app-heading-small">
                        <div class="icon icon-lg">
                            <span class="icon-alarm"></span>
                        </div>
                        <div class="title">
                            <h2>Notifications</h2>              
                            <p><strong>7 new</strong>, latest: July 19, 2016 at 10:14:32.</p>
                        </div>                                
                    </div>        
            
                    <div class="listing margin-bottom-10">                                                                                
                        <div class="listing-item margin-bottom-10">
                            <strong>Product Delivered</strong> <span class="label label-success pull-right">delivered</span>
                            <p class="margin-0 margin-top-5">#SPW-955-18 to st. StreetName SA, USA.</p>
                            <p class="text-muted">
                                <span class="fa fa-truck margin-right-5"></span> 19/07/2016 10:14:32 AM
                            </p>
                        </div>
                        <div class="listing-item margin-bottom-10">
                            <strong>Successful Payment</strong> <span class="label label-success pull-right">success</span>
                            <p class="margin-0 margin-top-5">Payment for order #SPW-955-17: <strong>$145.44</strong>.</p>
                            <p class="text-muted">
                                <span class="fa fa-bank margin-right-5"></span> 19/07/2016 09:55:12 AM
                            </p>
                        </div>
                        <div class="listing-item margin-bottom-10">
                            <strong>New Order #SPW-955-17</strong> <span class="label label-warning pull-right">waiting</span>
                            <p class="margin-0 margin-top-5">Added new order, waiting for payment. <a href="#">Order details</a>.</p>
                            <p class="text-muted">
                                <span class="fa fa-bank margin-right-5"></span> 19/07/2016 09:51:55 AM
                            </p>
                        </div>
                        <div class="listing-item margin-bottom-10">
                            <strong>Money Back Request</strong> <span class="label label-primary pull-right">return</span>
                            <p class="margin-0 margin-top-5">#SPW-955-17 return requested. <a href="#">Request details</a>.</p>
                            <p class="text-muted">
                                <span class="fa fa-bank margin-right-5"></span> 19/07/2016 08:44:51 AM
                            </p>
                        </div>
                        <div class="listing-item margin-bottom-10">
                            <strong>The critical amount of product</strong> <span class="label label-danger pull-right">important</span>
                            <p class="margin-0 margin-top-5">Product: <a href="#">Extra Awesome Product</a> (amount: <span class="text-danger">2</span>). <a href="#">Storehouse</a>.</p>
                            <p class="text-muted">
                                <span class="fa fa-cube margin-right-5"></span> 19/07/2016 08:30:00 AM
                            </p>
                        </div>
                        <div class="listing-item margin-bottom-10">
                            <strong>Product Delivery Start</strong> <span class="label label-warning pull-right">delivering</span>
                            <p class="margin-0 margin-top-5">#SPW-955-18 to st. StreetName SA, USA.</p>
                            <p class="text-muted">
                                <span class="fa fa-truck margin-right-5"></span> 18/07/2016 06:14:32 PM
                            </p>
                        </div>
                        <div class="listing-item margin-bottom-10">
                            <strong>Critical Server Load</strong> <span class="label label-danger pull-right">server</span>
                            <p class="margin-0 margin-top-5">Disk space: 248.1Gb/250Gb. <a href="#">Control panel</a>.</p>
                            <p class="text-muted">
                                <span class="fa fa-truck margin-right-5"></span> 18/07/2016 06:14:32 PM
                            </p>
                        </div>
                    </div>
                    <div class="row margin-bottom-30">
                        <div class="col-xs-6 col-xs-offset-3">
                            <button class="btn btn-default btn-block">All Notification</button>
                        </div>            
                    </div>
                    
                    <div class="app-heading app-heading-condensed app-heading-small margin-bottom-20">
                        <div class="icon icon-lg">
                            <span class="icon-cog"></span>
                        </div>
                        <div class="title">
                            <h2>Settings</h2>              
                            <p>Notification Settings</p>
                        </div>                                
                    </div>
                    
                    <div class="form-group">
                        <div class="row">
                            <div class="col-xs-2">
                                <label class="switch switch-sm margin-0">
                                    <input type="checkbox" name="app_settings_1" checked="" value="0">
                                </label>
                            </div>
                            <div class="col-xs-10">
                                <label>Delivery Information</label>
                            </div>
                        </div>            
                    </div>
                    <div class="form-group">
                        <div class="row">
                            <div class="col-xs-2">
                                <label class="switch switch-sm margin-0">
                                    <input type="checkbox" name="app_settings_2" checked="" value="0">
                                </label>
                            </div>
                            <div class="col-xs-10">
                                <label>Product Amount Information</label>
                            </div>
                        </div>            
                    </div>
                    <div class="form-group">
                        <div class="row">
                            <div class="col-xs-2">
                                <label class="switch switch-sm margin-0">
                                    <input type="checkbox" name="app_settings_3" checked="" value="0">
                                </label>
                            </div>
                            <div class="col-xs-10">
                                <label>Order Information</label>
                            </div>
                        </div>            
                    </div>
                    <div class="form-group">
                        <div class="row">
                            <div class="col-xs-2">
                                <label class="switch switch-sm margin-0">
                                    <input type="checkbox" name="app_settings_4" checked="" value="0">
                                </label>
                            </div>
                            <div class="col-xs-10">
                                <label>Server Load</label>
                            </div>
                        </div>            
                    </div>
                    <div class="form-group">
                        <div class="row">
                            <div class="col-xs-2">
                                <label class="switch switch-sm margin-0">
                                    <input type="checkbox" name="app_settings_5" value="0">
                                </label>
                            </div>
                            <div class="col-xs-10">
                                <label>User Registrations</label>
                            </div>
                        </div>            
                    </div>
                    <div class="form-group">
                        <div class="row">
                            <div class="col-xs-2">
                                <label class="switch switch-sm margin-0">
                                    <input type="checkbox" name="app_settings_6" value="0">
                                </label>
                            </div>
                            <div class="col-xs-10">
                                <label>Purchase Information</label>
                            </div>
                        </div>            
                    </div>
                    
                </div>
            </div>
            <!-- END APP SIDEPANEL -->
            
            <!-- APP OVERLAY -->
            <div class="app-overlay"></div>
            <!-- END APP OVERLAY -->
        </div>        
        <!-- END APP WRAPPER -->                
        
        <!-- START SCRIPTS -->
        <script type="text/javascript" src="<?php echo $this->serverUrl(); ?>/js/vendor/jquery/jquery.min.js"></script>
        <script type="text/javascript" src="<?php echo $this->serverUrl(); ?>/js/vendor/jquery/jquery-ui.min.js"></script>
        <script type="text/javascript" src="<?php echo $this->serverUrl(); ?>/js/vendor/bootstrap/bootstrap.min.js"></script>
        <script type="text/javascript" src="<?php echo $this->serverUrl(); ?>/js/vendor/moment/moment.min.js"></script>       
        
        <script type="text/javascript" src="<?php echo $this->serverUrl(); ?>/js/vendor/customscrollbar/jquery.mCustomScrollbar.min.js"></script>
        <script type="text/javascript" src="<?php echo $this->serverUrl(); ?>/js/vendor/bootstrap-select/bootstrap-select.js"></script>
        <script type="text/javascript" src="<?php echo $this->serverUrl(); ?>/js/vendor/select2/select2.full.min.js"></script>
        <script type="text/javascript" src="<?php echo $this->serverUrl(); ?>/js/vendor/bootstrap-datetimepicker/bootstrap-datetimepicker.js"></script>
        
        <script type="text/javascript" src="<?php echo $this->serverUrl(); ?>/js/vendor/maskedinput/jquery.maskedinput.min.js"></script>
        <script type="text/javascript" src="<?php echo $this->serverUrl(); ?>/js/vendor/form-validator/jquery.form-validator.min.js"></script>
        
        <script type="text/javascript" src="<?php echo $this->serverUrl(); ?>/js/vendor/noty/jquery.noty.packaged.js"></script>
        
        <script type="text/javascript" src="<?php echo $this->serverUrl(); ?>/js/vendor/datatables/jquery.dataTables.min.js"></script>
        <script type="text/javascript" src="<?php echo $this->serverUrl(); ?>/js/vendor/datatables/dataTables.bootstrap.min.js"></script>
        
        <script type="text/javascript" src="<?php echo $this->serverUrl(); ?>/js/vendor/sweetalert/sweetalert.min.js"></script>
        <script type="text/javascript" src="<?php echo $this->serverUrl(); ?>/js/vendor/knob/jquery.knob.min.js"></script>
        
        <script type="text/javascript" src="<?php echo $this->serverUrl(); ?>/js/vendor/jvectormap/jquery-jvectormap.min.js"></script>
        <script type="text/javascript" src="<?php echo $this->serverUrl(); ?>/js/vendor/jvectormap/jquery-jvectormap-world-mill-en.js"></script>
        <script type="text/javascript" src="<?php echo $this->serverUrl(); ?>/js/vendor/jvectormap/jquery-jvectormap-us-aea-en.js"></script>
        
        <script type="text/javascript" src="<?php echo $this->serverUrl(); ?>/js/vendor/sparkline/jquery.sparkline.min.js"></script>
        
        <script type="text/javascript" src="<?php echo $this->serverUrl(); ?>/js/vendor/morris/raphael.min.js"></script>
        <script type="text/javascript" src="<?php echo $this->serverUrl(); ?>/js/vendor/morris/morris.min.js"></script>
        
        <script type="text/javascript" src="<?php echo $this->serverUrl(); ?>/js/vendor/rickshaw/d3.v3.js"></script>
        <script type="text/javascript" src="<?php echo $this->serverUrl(); ?>/js/vendor/rickshaw/rickshaw.min.js"></script>
        
        <script type="text/javascript" src="<?php echo $this->serverUrl(); ?>/js/vendor/isotope/isotope.pkgd.min.js"></script>
        
        <script type="text/javascript" src="<?php echo $this->serverUrl(); ?>/js/vendor/dropzone/dropzone.js"></script>
        <script type="text/javascript" src="<?php echo $this->serverUrl(); ?>/js/vendor/nestable/jquery.nestable.js"></script>
        <script type="text/javascript" src="<?php echo $this->serverUrl(); ?>/js/vendor/cropper/cropper.min.js"></script>
        
        <script type="text/javascript" src="<?php echo $this->serverUrl(); ?>/js/vendor/tableexport/tableExport.js"></script>
        <script type="text/javascript" src="<?php echo $this->serverUrl(); ?>/js/vendor/tableexport/jquery.base64.js"></script>
        <script type="text/javascript" src="<?php echo $this->serverUrl(); ?>/js/vendor/tableexport/html2canvas.js"></script>
        <script type="text/javascript" src="<?php echo $this->serverUrl(); ?>/js/vendor/tableexport/jspdf/libs/sprintf.js"></script>
        <script type="text/javascript" src="<?php echo $this->serverUrl(); ?>/js/vendor/tableexport/jspdf/jspdf.js"></script>
        <script type="text/javascript" src="<?php echo $this->serverUrl(); ?>/js/vendor/tableexport/jspdf/libs/base64.js"></script> 
        
        <script type="text/javascript" src="<?php echo $this->serverUrl(); ?>/js/app.js"></script>
        <script type="text/javascript" src="<?php echo $this->serverUrl(); ?>/js/app_plugins.js"></script>
        <script type="text/javascript" src="<?php echo $this->serverUrl(); ?>/js/app_demo.js"></script>
        <!-- END SCRIPTS -->
        <script type="text/javascript" src="<?php echo $this->serverUrl(); ?>/js/app_demo_dashboard.js"></script>
    </body>
</html>