<?php
$title = 'Scraping';
$this->headTitle($title);
?>
<h1><?= $this->escapeHtml($title) ?></h1>
<p>
    <a class="btn btn-success pull-right" href="<?= $this->url('scraping', ['action' => 'plazavea']) ?>">Plaza Vea</a>
    <a class="btn btn-success pull-right" href="<?= $this->url('scraping', ['action' => 'tottus']) ?>">Tottus</a>
    <a class="btn btn-success pull-right" href="<?= $this->url('scraping', ['action' => 'wong']) ?>">Wong</a>
</p>