            <div class="app-container">
                
                <div class="app-login-box">                                        
                    <div class="app-login-box-user"><img src="/img/user/no-image.png" alt="Usuario"></div>
                    <div class="app-login-box-title">
                        <div class="title">Ya eres usuario?</div>
                        <div class="subtitle">Iniciar sesión en su cuenta</div>                        
                    </div>
                    <div class="app-login-box-container">
                        <form action="" method="post">
                            <div class="form-group">
                                <input type="text" class="form-control" name="login" placeholder="Dirección de correo electrónico">
                            </div>
                            <div class="form-group">
                                <input type="password" class="form-control" name="password" placeholder="Contraseña">
                            </div>
                            <div class="form-group">

                                <div class="row">
                                    <div class="col-md-6 col-xs-6">
                                        <div class="app-checkbox">
                                            <label><input type="checkbox" name="app-checkbox-1" value="0"> Recuérdame</label>
                                        </div>
                                    </div>
                                    <div class="col-md-6 col-xs-6">
                                        <button class="btn btn-success btn-block">Registrarse</button>
                                    </div>
                                </div>
                                
                            </div>
                        </form>
                    </div>
                    <div class="app-login-box-or">
                        <div class="or">OR</div>
                    </div>
                    <div class="app-login-box-container">
                        <button class="btn btn-facebook btn-block">Conéctate con Facebook</button>
                        <button class="btn btn-twitter btn-block">Conéctate con Twitter</button>
                    </div>
                    <div class="app-login-box-footer">
                        &copy; Idealshop 2016. All rights reserved.
                    </div>
                </div>
                                
            </div>