            <div class="app-container">
                
                <div class="app-login-box">
                    <div class="app-login-box-title padding-top-30">
                        <div class="title">Regístrate</div>
                        <div class="subtitle">Únete a nuestra comunidad con el correo electrónico</div>                        
                    </div>                    
                    <div class="app-login-box-container margin-top-20">                                                
                        <button class="btn btn-facebook btn-block">Conéctate con With Facebook</button>
                        <button class="btn btn-twitter btn-block">Conéctate con Twitter</button>
                    </div>
                    <div class="app-login-box-container margin-top-20">
                        <div class="title">Inicia sesión con el correo electrónico</div>
                        <form action="" method="post">
                            <div class="form-group">
                                <div class="row">
                                    <div class="col-md-6">
                                        <input type="text" class="form-control" name="name" placeholder="Nombre">
                                    </div>
                                    <div class="col-md-6">
                                        <input type="text" class="form-control" name="last_name" placeholder="Apellidos">
                                    </div>
                                </div>                                
                            </div>
                            <div class="form-group">
                                <input type="text" class="form-control" name="login" placeholder="Correo electrónico">
                            </div>
                            <div class="form-group">
                                <input type="password" class="form-control" name="password" placeholder="contraseña">
                            </div>                            
                            <div class="form-group">                                
                                <button class="btn btn-success btn-block">Crear una cuenta</button>                                
                            </div>
                        </form>
                    </div>                           
                    <div class="app-login-box-footer">
                        &copy; Idealshop 2016. All rights reserved.
                    </div>
                </div>
                                
            </div>